volumes:
  grafana_data:
  graphite_data:

networks:
  stats:
    driver: bridge

x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "5"

services:
  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - ./logs/graphite:/var/log
      - ./grafanaConfig/graphite:/opt/graphite/conf
      - graphite_data:/opt/graphite/storage
    networks:
      - stats
    logging: *default-logging
  grafana:
    image: grafana/grafana-oss:9.3.6-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafanaConfig/grafana:/etc/grafana
      - ./logs/grafana:/var/log/grafana
    ports:
      - 3000:3000
    healthcheck:
      test: "curl -fsSL -o /dev/null http://localhost:3000/login"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - stats
    logging: *default-logging
  stats-getter:
    build:
      context: .
      dockerfile: ./src/pushStats/Dockerfile
    volumes:
      - ./logs/statsGetter:/app/logs
    depends_on:
      - graphite
    environment:
      - PREFIX=
      - SERVER_PORT=21025
      - PUSH_STATUS_PORT=
    networks:
      - stats
    logging: *default-logging