{
 "title": "Service info",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "target": "carbon.*.*.cpuUsage" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.*.memUsage, 2)"
    }
   ]
  },
  {
   "title": "Metrics recieved",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "groupByNode(aliasByNode(carbon.*.*.metricsReceived, 3), 0, 'sumSeries')"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(stats.statsd.processing_time, 'Total')"
    }
   ]
  },
  {
   "title": "Timestamp lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.statsd.timestamp_lag"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "groupByNode(alias(carbon.agents.*.cache.size, 'Total'), 0, 'sum')"
    }
   ]
  }
 ]
}